generator:
  _target_: audyn.models.wavenext.WaveNeXtVocoder
  in_channels: ${data.melspectrogram.n_mels}
  out_channels: 1
  hidden_channels: 16
  bottleneck_channels: 64
  kernel_size: 5
  norm: layer_norm
  activation: gelu
  pre_kernel_size: 5
  post_kernel_size: 256
  post_stride:
  num_blocks: 2

discriminator:
  _target_: audyn.models.hifigan.Discriminator
  period_discriminator:
    _target_: audyn.models.hifigan.MultiPeriodDiscriminator
    _convert_: all
    period: [2, 3, 5]
    num_features: [1, 2, 2, 4]
    kernel_size: [3, 3, 5, 5]
    stride: [1, 2, 2, 4]
    weight_regularization: ["weight_norm", "weight_norm", "weight_norm"]
  scale_discriminator:
    _target_: audyn.models.hifigan.MultiScaleDiscriminator
    _convert_: all
    num_features: [1, 2, 2, 4]
    kernel_size: [3, 3, 5, 5]
    stride: [1, 2, 2, 4]
    dilation: [1, 1, 1, 1]
    pool_kernel_size: 4
    pool_stride: 2
    weight_regularization: ["spectral_norm", "weight_norm", "weight_norm"]
