defaults:
  - ast

embedding:
  _target_: audyn.modules.vit.PatchEmbedding
  kernel_size:
    - ${data.melspectrogram.n_mels}
    - ?
  stride:
    - ${..kernel_size.0}
    - ?
backbone:
  encoder_layer:
    _target_: audyn.models.lextransformer.LEXTransformerEncoderLayer
