_target_: audyn.criterion.MultiCriteria
cross_entropy:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: torch.nn.CrossEntropyLoss
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: estimated_indices
    target:
      target: indices
