defaults:
  - record: pixelcnn
  - dataset: torch
  - dataloader: default
  - _self_

dataloader:
  train:
    batch_size: 32
  validation:
    batch_size: 32

key_mapping:
  train:
    input:
      input: indices_slice
    output: estimated_indices
  validation: ${.train}
  inference:
    input:
      initial_state: initial_index
      height: height
      width: width
    output: estimated_indices

clip_gradient:
  _target_: audyn.utils.GradClipper
  mode: norm
  max_norm: 10

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 5000
      path: ${...exp_dir}/model/pixelcnn/iteration{iteration}.pth
    epoch:
      every: 20
      path: ${...exp_dir}/model/pixelcnn/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/pixelcnn/last.pth
    best_epoch:
      path: ${...exp_dir}/model/pixelcnn/best_epoch.pth

steps:
  epochs: 10
  iterations:
  lr_scheduler: epoch
