defaults:
  - record: vqvae
  - dataset: torch
  - dataloader: default
  - _self_

dataloader:
  train:
    batch_size: 32
  validation:
    batch_size: 32

key_mapping:
  train:
    input:
      input: log_melspectrogram_slice
    output:
      - reconstructed
      - encoded
      - quantized
      - indices
  validation: ${.train}
  inference:
    input:
      quantized: codebook_indices
    output: reconstructed

clip_gradient:
  _target_: audyn.utils.GradClipper
  mode: norm
  max_norm: 10

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 5000
      path: ${...exp_dir}/model/vqvae/iteration{iteration}.pth
    epoch:
      every: 20
      path: ${...exp_dir}/model/vqvae/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/vqvae/last.pth
    best_epoch:
      path: ${...exp_dir}/model/vqvae/best_epoch.pth

steps:
  epochs: 10
  iterations:
  lr_scheduler:
