defaults:
  - record: default
  - dataset: wordnet-mammel
  - dataloader: wordnet-mammel
  - _self_

trainer:
  _target_: audyn.utils.driver.BaseTrainer

key_mapping:
  train:
    input:
      anchor: anchor
      positve: positve
      negative: negative
    output:
      - anchor_embedding
      - positve_embedding
      - negative_embedding
  validation: ${.train}

clip_gradient:

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 5000
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 100
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs: 300
  iterations:
  lr_scheduler: epoch
