defaults:
  - _mnist
  - _self_

train:
  _target_: utils.dataset.GumbelMNIST
  root: "../data/"
  init_temperature: 2
  min_temperature: 0.5
  gamma: 0.999
  schedule: exponential
  train: true
  transform:
    _target_: torchvision.transforms.ToTensor
  target_transform:
    _target_: torch.tensor
    _partial_: true
  download: true

validation:
  _target_: utils.dataset.MNIST
  root: ${..train.root}
  train: false
  transform: ${..train.transform}
  target_transform: ${..train.target_transform}
  download: ${..train.download}
