train:
  _target_: audyn.utils.data.dataset.SortableTorchObjectDataset
  list_path:
  feature_dir:
  sort_key:
validation:
  _target_: audyn.utils.data.dataset.TorchObjectDataset
  list_path:
  feature_dir:
