defaults:
  - dataset: defaults
  - dataloader: defaults
  - clip_gradient: defaults
  - record: defaults
  - _self_

trainer:
  
key_mapping:

ddp_kwargs:

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 20000
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 100
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs:
  iterations: 100000
  lr_scheduler:
