defaults:
  - dataset: defaults
  - dataloader: defaults
  - record: defaults
  - _self_

key_mapping:
  train:
    generator:
      input:
        noise: noise
      output: fake
    discriminator:
      fake:
        input:
          waveform: ${....generator.output}
        output: fake_prob
      real:
        input:
          waveform: input
        output: real_prob
  validation: ${.train}

ddp_kwargs:

clip_gradient:

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 20000
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 100
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs:
  iterations: 100000
  lr_scheduler:
    generator: iteration
    discriminator: iteration
