defaults:
  - dataset: defaults
  - dataloader: defaults
  - clip_gradient: defaults
  - record: defaults
  - _self_
  
key_mapping:
  train:
    input:
      input: waveform
      local_conditioning: log_melspectrogram
    output: estimated_waveform
  validation: ${.train}
  inference:
    input:
      initial_state: initial_waveform
      local_conditioning: ${...train.input.local_conditioning}
      max_length: max_waveform_length
    output: estimated_waveform

ddp_kwargs:

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 20000
      path: ${...exp_dir}/model/iteration{iteration}.pth
    epoch:
      every: 100
      path: ${...exp_dir}/model/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/last.pth
    best_epoch:
      path: ${...exp_dir}/model/best_epoch.pth

steps:
  epochs:
  iterations: 100000
  lr_scheduler:
