_target_: audyn.models.ConvTasNet.build_from_config
encoder:
  _target_: audyn.models.tasnet.Encoder
  in_channels: 1
  num_basis: 512
  kernel_size: 16
  stride: 8
  nonlinear: relu
decoder:
  _target_: audyn.models.tasnet.Decoder
  out_channels: ${..encoder.in_channels}
  num_basis: ${..encoder.num_basis}
  kernel_size: ${..encoder.kernel_size}
  stride: ${..encoder.stride}
bottleneck_channels: 128
hidden_channels: 256
skip_channels: 128
kernel_size: 3
num_blocks: 3
num_layers: 8
dilated: true
separable: true
nonlinear: prelu
norm: true
mask_nonlinear: sigmoid
is_causal: true
num_sources: 2
