defaults:
  - default
  - _self_

train:
  _target_: audyn.utils.data.fma.FreeMusicArchiveNAFPDataset
  list_path:
  feature_dir:
  background_list_path:
  impulse_response_list_path:

validation:
  _target_: ${..train._target_}
  list_path:
  feature_dir:
  background_list_path:
  impulse_response_list_path:
