_target_: audyn.criterion.MultiCriteria
reconstruction_loss:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: torch.nn.MSELoss
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: ???
    target:
      target: ???
codebook_loss:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: audyn.criterion.vqvae.CodebookLoss
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      encoded: ???
      quantized: ???
    target:
commitment_loss:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: audyn.criterion.vqvae.CommitmentLoss
    reduction: mean
  weight: 0.25
  key_mapping:
    estimated:
      encoded: ???
      quantized: ???
    target:
