_target_: audyn.criterioni.MultiCriteria
reconstruction:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: audyn.criterion.ssast.ReconstructionLoss
    reduction: mean
  weight: 10
  key_mapping:
    estimated:
      input: reconstruction_output
      target: reconstruction_target
      length: reconstruction_length
    target:
classification:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: audyn.criterion.ssast.ClassificationLoss
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: classification_output
      target: classification_target
      length: classification_length
    target:
