_target_: audyn.criterion.MultiCriteria
mse_period_generator:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: audyn.criterion.sdr.PITNegSISDR
    target: 1
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: estimated_waveform
    target:
      target: waveform
