_target_: audyn.criterion.base.MultiCriteria
cross_entropy:
  _target_: audyn.criterion.base.BaseCriterionWrapper
  criterion:
    _target_: audyn.criterion.autoregressive.AutoRegressiveWrapper
    criterion:
      _target_: torch.nn.CrossEntropyLoss
      reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: estimated_waveform_slice_mulaw
    target:
      target: waveform_slice_mulaw
