defaults:
  - record: valle
  - dataset: torch
  - dataloader: default
  - key_mapping: valle
  - _self_

dataloader:
  train:
    batch_size: 32
  validation:
    batch_size: 1

clip_gradient:
  generator:
    _target_: audyn.utils.GradClipper
    mode: norm
    max_norm: 10
  discriminator: ${.generator}

ddp_kwargs:
  find_unused_parameters: true

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard/valle"
  save_checkpoint:
    iteration:
      every: 50000
      path: ${...exp_dir}/model/valle/iteration{iteration}.pth
    epoch:
      every: 200
      path: ${...exp_dir}/model/valle/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/valle/last.pth
    best_epoch:
      path: ${...exp_dir}/model/valle/best_epoch.pth

steps:
  epochs:
  iterations: 200000
  lr_scheduler:
    generator:
    discriminator:
