_target_: audyn.models.vqvae.VQVAE
encoder:
  _target_: utils.models.vqvae.Encoder
  in_channels: 1
  out_channels: ${..embedding_dim}
  hidden_channels: 64
  stride: 2
  num_layers: 2
decoder:
  _target_: utils.models.vqvae.Decoder
  in_channels: ${..embedding_dim}
  out_channels: ${..encoder.in_channels}
  hidden_channels: ${..encoder.hidden_channels}
  stride: ${..encoder.stride}
  num_layers: ${..encoder.num_layers}
codebook_size: ${data.codebook.size}
embedding_dim: 32
