defaults:
  - system: default
  - preprocess: default
  - data: default
  - train: default
  - test: default
  - model: default
  - optimizer:
  - lr_scheduler: default
  - criterion:
  - _self_

hydra:
  job:
    chdir: false
  run:
    dir: "./log/${now:%Y%m%d-%H%M%S}"
