_target_: audyn.criterion.MultiCriteria
neg_sisdr:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: audyn.criterion.sdr.PITNegSISDR
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: separated_slice
    target:
      target: sources_slice
