defaults:
  - default
  - _self_

train:
  batch_size: 16
  collate_fn:
    _target_: audyn.utils.data.Collator
    composer:
      _target_: audyn.utils.data.SequentialComposer
      _args_:
        - _target_: audyn.utils.data.Mixer
          input_keys:
            - drums
            - bass
            - other
            - vocals
          output_key: mixture
          decode_audio_as_waveform: true
          decode_audio_as_monoral: true
        - _target_: audyn.utils.data.Stacker
          input_keys: ${..0.input_keys}
          output_key: sources
          dim: 0
          decode_audio_as_waveform: ${..0.decode_audio_as_waveform}
          decode_audio_as_monoral: ${..0.decode_audio_as_monoral}
  shuffle:
validation:
  batch_size: 16
  collate_fn: ${..train.collate_fn}
