# Binary cross entropy for multi-label estimation

_target_: audyn.criterion.MultiCriteria
cross_entropy:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: torch.nn.BCEWithLogitsLoss
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: ???
    target:
      target: ???
