_target_: audyn.models.ConvTasNet.build_from_config
encoder:
  _target_: audyn.models.tasnet.Encoder
  in_channels: 1
  num_basis: 32
  kernel_size: 16
  stride: 8
  nonlinear: relu
decoder:
  _target_: audyn.models.tasnet.Decoder
  out_channels: ${..encoder.in_channels}
  num_basis: ${..encoder.num_basis}
  kernel_size: ${..encoder.kernel_size}
  stride: ${..encoder.stride}
bottleneck_channels: 8
hidden_channels: 8
skip_channels: 8
kernel_size: 3
num_blocks: 2
num_layers: 2
dilated: true
separable: true
nonlinear: prelu
norm: true
mask_nonlinear: sigmoid
is_causal: true
num_sources: ${data.sources.num_sources}
