_target_: audyn.criterion.MultiCriteria
binary_cross_entropy:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: torch.nn.BCEWithLogitsLoss
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: logit
    target:
      target: tags
