_target_: audyn.models.bsrnn.BandSplitRNN
bandsplit:
  _target_: audyn.modules.bsrnn.MultiChannelBandSplitModule
  in_channels: 2
  bins:
    _target_: builtins.list
    _args_:
      - - 5
        - 5
        - 4
        - 5
        - 5
        - 4
        - 5
        - 5
        - 4
        - 5
        - 12
        - 11
        - 12
        - 11
        - 12
        - 12
        - 11
        - 12
        - 11
        - 12
        - 12
        - 11
        - 23
        - 24
        - 23
        - 23
        - 23
        - 24
        - 23
        - 23
        - 46
        - 47
        - 46
        - 47
        - 46
        - 47
        - 46
        - 47
        - 92
        - 93
        - 96
  embed_dim: 128
bandmerge:
  _target_: audyn.modules.bsrnn.MultiChannelBandMergeModule
  out_channels: ${..bandsplit.in_channels}
  bins: ${..bandsplit.bins}
  embed_dim: ${..bandsplit.embed_dim}
  hidden_channels: 512
backbone:
  _target_: audyn.modules.bsrnn.BandSplitRNNBackbone
  num_features: ${..bandsplit.embed_dim}
  hidden_channels: 256
  num_blocks: 6
  is_causal: false
  norm: true
  rnn: lstm
  eps: 1.0e-5
