generator:
  _target_: audyn.criterion.base.MultiCriteria
  waveform_fm:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.FeatureMatchingLoss
    weight: 100
    key_mapping:
      estimated:
        input: waveform_fake_feature_map
        target: waveform_real_feature_map
      target:
  waveform_adversarial:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.MSELoss
      target: 1
      reduction: mean
    weight: 1
    key_mapping:
      estimated:
        input: waveform_fake_prob
      target:
  melspectrogram:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.melspectrogram.MelSpectrogramL1Loss
      sample_rate: ${data.audio.sample_rate}
      n_fft: ${data.spectrogram.n_fft}
      hop_length: ${data.spectrogram.hop_length}
      f_min: ${data.melspectrogram.f_min}
      f_max: ${data.melspectrogram.f_max}
      n_mels: ${data.melspectrogram.n_mels}
      take_log: true
      reduction: mean
    weight: 45
    key_mapping:
      estimated:
        input: estimated_waveform_slice
      target:
        target: waveform_slice
  codebook_entropy:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.rvqvae.CodebookEntropyLoss
      codebook_size: ${data.codebook.size}
    weight: 0  # monitoring
    key_mapping:
      estimated:
        input: codebook_indices
      target:
  codebook_loss:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.rvqvae.CodebookLoss
    weight: 0  # monitoring
    key_mapping:
      estimated:
        encoded: encoded
        quantized: quantized
      target:
  commitment_loss:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.vqvae.CommitmentLoss
      reduction: mean
    weight: 0.25
    key_mapping:
      estimated:
        encoded: encoded
        quantized: quantized
      target:
discriminator:
  _target_: audyn.criterion.base.MultiCriteria
  waveform_discriminator_fake:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.MSELoss
      target: 0
      reduction: mean
    weight: 1
    key_mapping:
      estimated:
        input: waveform_fake_prob
      target:
  waveform_discriminator_real:
    _target_: audyn.criterion.base.BaseCriterionWrapper
    criterion:
      _target_: audyn.criterion.hifigan.MSELoss
      target: 1
      reduction: mean
    weight: 1
    key_mapping:
      estimated:
        input: waveform_real_prob
      target:
