_target_: audyn.criterion.MultiCriteria
spectrogram:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: audyn.criterion.contrastive.InterNTXentLoss
    dim: 0
  weight: 1
  key_mapping:
    estimated:
      input: embedding
      other: augmented_embedding
    target:
