- name: adam
  optimizer:
    _target_: torch.optim.Adam
    lr: 2.0e-4
  modules:
    - encoder
    - decoder
- name: ema
  optimizer:
    _target_: audyn.optim.optimizer.ExponentialMovingAverageCodebookOptimizer
  modules:
    - vector_quantizer
