defaults:
  - dataset: torch
  - dataloader: default
  - record: pixelsnail
  - clip_gradient: pixelsnail
  - _self_

dataloader:
  train:
    batch_size: 8
  validation:
    batch_size: 8

key_mapping:
  train:
    input:
      input: indices
      conditioning: category
    output: estimated_indices
  validation: ${.train}
  inference:
    input:
      initial_state: initial_index
      conditioning: category
      height: height
      width: width
    output: estimated_indices

resume:
  continue_from:

output:
  exp_dir: "./exp"
  tensorboard_dir: "./tensorboard"
  save_checkpoint:
    iteration:
      every: 200000
      path: ${...exp_dir}/model/pixelsnail/iteration{iteration}.pth
    epoch:
      every: 500
      path: ${...exp_dir}/model/pixelsnail/epoch{epoch}.pth
    last:
      path: ${...exp_dir}/model/pixelsnail/last.pth
    best_epoch:
      path: ${...exp_dir}/model/pixelsnail/best_epoch.pth

steps:
  epochs: 1500
  iterations:
  lr_scheduler:
