_target_: audyn.criterion.MultiCriteria
classification:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: utils.criterion.IntraInfoNCELoss
    dim: 1
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: classified_patch
      target: target_patch
      length: patch_length
    target:
reconstruction:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: utils.criterion.ReconstructionLoss
    reduction: mean
  weight: 10
  key_mapping:
    estimated:
      input: reconstructed_patch
      target: target_patch
      length: patch_length
    target:
