_target_: audyn.criterion.MultiCriteria
nll:
  _target_: audyn.criterion.BaseCriterionWrapper
  criterion:
    _target_: audyn.criterion.flow.GaussFlowLoss
    std: ${data.noise_std.train}
    reduction: mean
  weight: 1
  key_mapping:
    estimated:
      input: latent
      logdet: logdet
    target:
