name: Build wheels

on:
  pull_request:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-15-intel
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build wheels
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "*-win32 *_i686 pp* *-musllinux_* cp313-macosx_x86_64"  # for PyTorch
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
            auditwheel repair -w {dest_dir} {wheel} 
            --exclude libtorch_cpu.so 
            --exclude libtorch.so
            --exclude libc10.so
            --exclude libtorch_python.so
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
            delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}
            --exclude libtorch_cpu.dylib 
            --exclude libtorch.dylib
            --exclude libc10.dylib
            --exclude libtorch_python.dylib
            --ignore-missing-dependencies
          CIBW_BUILD_VERBOSITY: 1
        uses: pypa/cibuildwheel@v3.4.0
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: python-package-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
