name: install ffmpeg on MacOS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install:
    name: Install ffmpeg on MacOS
    runs-on: macos-13
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        torch-version: ["1.9.0", "1.11.0", "2.0.0", "2.1.0", "2.2.0"]
        exclude:
          # skip torch==1.9 and 1.11 for the time being
          - torch-version: "1.9.0"
          - torch-version: "1.11.0"
          - python-version: "3.10"
            torch-version: "1.9.0"
          - python-version: "3.11"
            torch-version: "1.9.0"
          - python-version: "3.11"
            torch-version: "1.11.0"
          - python-version: "3.11"
            torch-version: "2.2.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,tests]"
      - name: Show dependencies
        run: |
          pip list
      - name: Show backend of torchaudio
        run: |
          python -c "import torchaudio; print(torchaudio.list_audio_backends())"
          python -c "import torchaudio; assert len(torchaudio.list_audio_backends()) > 0"
