name: install ffmpeg on MacOS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install:
    name: Install ffmpeg on MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        torch-version: ["1.9.0", "1.11.0", "2.0.0", "2.1.0", "2.2.0"]
        exclude:
          # skip torch==1.9 and 1.11 for the time being
          - torch-version: "1.9.0"
          - torch-version: "1.11.0"
          - python-version: "3.10"
            torch-version: "1.9.0"
          - python-version: "3.11"
            torch-version: "1.9.0"
          - python-version: "3.11"
            torch-version: "1.11.0"
          - python-version: "3.11"
            torch-version: "2.2.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ffmpeg (MacOS)
        run: |
          # torchaudio supports ffmpeg<7
          # https://pytorch.org/audio/stable/installation.html
          brew install ffmpeg@4
          echo "/opt/homebrew/opt/ffmpeg@4/bin" >> $GITHUB_PATH
          echo "LDFLAGS=-L/opt/homebrew/opt/ffmpeg@4/lib" >> "$GITHUB_ENV"
          echo "CPPFLAGS=-I/opt/homebrew/opt/ffmpeg@4/include" >> "$GITHUB_ENV"
          echo "PKG_CONFIG_PATH=/opt/homebrew/opt/ffmpeg@4/lib/pkgconfig" >> "$GITHUB_ENV"
          echo "LD_LIBRARY_PATH=/opt/homebrew/opt/ffmpeg@4/lib" >> "$GITHUB_ENV"
          echo "FFMPEG_ROOT=/opt/homebrew/opt/ffmpeg@4" >> "$GITHUB_ENV"
          echo "/opt/homebrew/opt/ffmpeg@4/lib" >> $GITHUB_PATH
      - name: Show ffmpeg utility (MacOS)
        run: |
          echo ${LD_LIBRARY_PATH}
      - name: Install dependencies
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.13'
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,tests]"
      - name: Show dependencies
        run: |
          pip list
      - name: Show backend of torchaudio
        run: |
          python -c "import torchaudio; print(torchaudio.list_audio_backends())"
          python -c "import torchaudio; assert len(torchaudio.list_audio_backends()) > 0"
