name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
      - name: Set up Python 3.13
        run: |
          uv python install
          uv venv
      - name: Install dependencies
        run: |
          uv pip install --upgrade pip
          uv pip install -e ".[dev]"
      - name: Run linters
        run: |
          uv run ruff check audyn
      - name: Run formatters
        run: |
          uv run ruff format --check audyn
