name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install dependencies (Ubuntu)
        run: |
          . tests/scripts/free_ubuntu_disk.sh
          . tests/scripts/install_ubuntu_dependencies.sh
      - name: Install dependencies
        run: |
          uv venv --python 3.13
          source .venv/bin/activate
          uv pip install -e ".[dev]"
      - name: Run linters
        run: |
          ruff check audyn
      - name: Run formatters
        run: |
          ruff format --check audyn tests
