name: windows-latest/3.13/2.8
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  package:
    uses: ./.github/workflows/test_package_windows-latest.yaml
    with:
      # https://github.com/python/cpython/issues/125235
      python-version: "3.13.1"
      torch-version: "2.8.0"
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
