name: test package on windows-latest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  package:
    uses: ./.github/workflows/test_package_windows-latest.yaml
    with:
      python-version: "3.8"
      torch-version: "2.1.0"
