name: test package on macos-13
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      torch-version:
        required: true
        type: string
jobs:
  package:
    uses: ./.github/workflows/test_package_main.yaml
    with:
      os: macos-13
      python-version: ${{ inputs.python-version }}
      torch-version: ${{ inputs.torch-version }}
