name: windows-latest/3.9/2.0
on:
  workflow_run:
    workflows:
      - "windows-latest/3.12/2.6"
    types:
      - completed
jobs:
  package:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/test_package_windows-latest.yaml
    with:
      python-version: "3.9"
      torch-version: "2.0.0"
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
