name: test package on macos-13
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  package:
    uses: ./.github/workflows/test_package_macos-13.yaml
    with:
      python-version: "3.11"
      torch-version: "2.1.0"
    secrets:
      ACCESS_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
