name: test package on windows-latest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  package:
    uses: ./.github/workflows/test_package_windows-latest.yaml
    with:
      python-version: "3.11"
      torch-version: "2.0.0"
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
