name: Tests for docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install dependencies (Ubuntu)
        run: |
          . tests/scripts/free_ubuntu_disk.sh
          . tests/scripts/install_ubuntu_dependencies.sh
      - name: Overwrite torch version in pyproject.toml (Ubuntu & MacOS)
        if: ${{ inputs.os != 'windows-latest' }}
        env:
          PYTHON_VERSION: "3.13"
          TORCH_VERSION: "2.6"
        run: |
          uv venv --python ${PYTHON_VERSION}
          source .venv/bin/activate
          uv pip install packaging
          python tests/scripts/overwrite_pyproject_toml.py --path pyproject.toml --torch-version ${TORCH_VERSION}
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install ".[docs]"
      - name: Build docs
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          source .venv/bin/activate
          cd docs/
          uv run --active sphinx-build -W ./ ./_build/html/
