name: ubuntu-latest/3.10/2.2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  package:
    uses: ./.github/workflows/test_package_ubuntu-latest.yaml
    with:
      python-version: "3.10"
      torch-version: "2.2.0"
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
