name: Tests for docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install dependencies (Ubuntu)
        if: ${{ runner.os == 'Linux' }}
        run: |
          . tests/scripts/free_ubuntu_disk.sh
          . tests/scripts/install_ubuntu_dependencies.sh
      - name: Install dependencies
        run: |
          uv pip install --system ".[docs]"
      - name: Build docs
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd docs/
          uv run sphinx-build -W ./ ./_build/html/
