name: ubuntu-latest/3.12/2.3
on:
  workflow_run:
    workflows:
      - ubuntu-latest/3.12/2.6
    types:
      - completed
jobs:
  package:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/test_package_ubuntu-latest.yaml
    with:
      python-version: "3.12"
      torch-version: "2.3.0"
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
