name: test package on windows-latest
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      torch-version:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
        type: string
jobs:
  package:
    uses: ./.github/workflows/test_package_main.yaml
    with:
      os: windows-latest
      python-version: ${{ inputs.python-version }}
      torch-version: ${{ inputs.torch-version }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
