name: test package on windows-latest
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      torch-version:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true
jobs:
  package:
    uses: ./.github/workflows/test_package_main.yaml
    with:
      os: windows-latest
      python-version: ${{ inputs.python-version }}
      torch-version: ${{ inputs.torch-version }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

# NOTE: torch-2.2 on Windows
#       https://github.com/pytorch/pytorch/issues/116056
# NOTE: torch-2.3 on Windows
#       https://github.com/pytorch/pytorch/issues/125109
