name: ubuntu-latest/3.12/2.6
on:
  workflow_run:
    workflows:
      - "lint"
    types:
      - completed
jobs:
  package:
    uses: ./.github/workflows/test_package_ubuntu-latest.yaml
    with:
      python-version: "3.12"
      torch-version: "2.6.0"
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
